### ISSUE TITLE
OCP5 unresponsive, control plane seem to run havoc

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#139]
console not reachable, 2 control nodes showing as 100% memory / CPU in RHEV:
<img width="1119" alt="image" src="https://github.com/stormshift/support/assets/18532443/153d943d-ef2c-4646-8037-d5c0ee8157bc">
also saw tons of IO on netapp from OCP5. moved disk to storm3 to offload netapp. still an issue.
I

**Comment by DanielFroehlich** [comment]
@DanielFroehlich would you mind doing your magic?

**Comment by DanielFroehlich** [comment]
@rbo would you mind doing your magic?

**Comment by rbo** [comment]
ocp5-control-0, ocp5-control-1 do not responde via SSH

API is not available:
```
E0630 17:47:14.570131  662718 memcache.go:238] couldn't get current server API group list: Get "https://api.ocp5.stormshift.coe.muc.redhat.com:6443/api?timeout=32s": dial tcp 10.32.105.45:6443: connect: connection refused
```

Console looks good. => Reboot ocp5-control-0, ocp5-control-1 via rhev

**Comment by rbo** [comment]
doubled cpu & memory of control plane nodes - reboot all and removed masterscheduleable 

```
NAME                 STATUS   ROLES    AGE    VERSION
ocp5-control-0       Ready    master   370d   v1.25.8+37a9a08
ocp5-control-1       Ready    master   370d   v1.25.8+37a9a08
ocp5-control-2       Ready    master   370d   v1.25.8+37a9a08
ucs-blade-server-5   Ready    worker   37d    v1.25.8+37a9a08
ucs-blade-server-6   Ready    worker   37d    v1.25.8+37a9a08
ucs-blade-server-7   Ready    worker   142d   v1.25.8+37a9a08
ucs-blade-server-8   Ready    worker   143d   v1.25.8+37a9a08
```

**Comment by rbo** [comment]
Hope that stablelize a bit the controle plane

**Comment by rbo** [comment]
Let's wait a bit... give openshift the time to recover

**Comment by rbo** [comment]
Disk device /dev/nvme0n1 not accessible on host ocp5-control-0. - mh not good

**Comment by rbo** [comment]
Drain all the control plane node to remove the "worker" workload. Changed back the CPU & RAM it will be updated at the next reboot of the VM's. 

Cluster looks good for me.

![image](https://github.com/stormshift/support/assets/36604/b15cd088-6656-4874-b96d-a8ef1a4834b1)

**Comment by rbo** [comment]
@stefan-bergstein please a look and close the ticket.

**Comment by stefan-bergstein** [comment]
Removing  master scheduleable made ODF unscheduleable, because ODF must run on the control nodes, because the nvme are on the control nodes (VM with PCI passthrough):

- Ensured that ocs label is set: `oc get nodes | grep ocp5-control- | awk '{print $1} ' | while read f; do echo $f; oc label node $f cluster.ocs.openshift.io/openshift-storage="" ; done`
- Added taint:  `oc get nodes | grep ocp5-control- | awk '{print $1} ' | while read f; do echo $f; oc adm taint node $f node.ocs.openshift.io/storage="true":NoSchedule  ; done`
- Made control nodes scheduleable: ` oc edit schedulers.config.openshift.io cluster` -> `mastersSchedulable: true`

**Comment by stefan-bergstein** [comment]
ODF recovered, but control nodes with ODF should have 40GB (16+24) memory and 24 vCPU (16+8) each. 
Anyway, let's still try with limited resources because the should not be a lot of load on the cluster:
![image](https://github.com/stormshift/support/assets/19570494/0b4d3374-eeb5-4832-a90c-c999e0e6173d)

**Comment by stefan-bergstein** [comment]
@rbo please have look at my comments and let me know if this approach is okay.

**Comment by stefan-bergstein** [comment]
The taint on the control nodes was not that great. Removed it
```
  taints:
    - key: node.ocs.openshift.io/storage
      value: 'true'
      effect: NoSchedule
```

**Comment by DanielFroehlich** [comment]
OCP5 looks healthy, closing this issue
